name: 'Setup tools for WaaS'
description: 'Setup a WaaS tool environment and add it to the path'
author: 'METRO.digital'
inputs:
  version:
    description: 'waas schema version (e.g. waas/v1alpha3) for which tools should set up'
    required: true
runs:
  using: 'node12'
  main: 'dist/index.js'
