name: CI
on:
  pull_request:
  push:
    branches:
      - main
      - 'releases/*'

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: |
          npm ci
      - run: |
          npm run lint
  test-unit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: |
          npm ci
      - run: |
          npm run test
  test-integration_waas_v1alpha3:
    name: 'waas/v1alpha3'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: 'waas/v1alpha3'
        uses: ./
        with:
          version: 'waas/v1alpha3'
  test-integration_waas_v1alpha4:
    name: 'waas/v1alpha4'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: 'waas/v1alpha4'
        uses: ./
        with:
          version: 'waas/v1alpha4'
  test-integration_waas_v1beta1:
    name: 'waas/v1beta1'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: 'waas/v1beta1'
        uses: ./
        with:
          version: 'waas/v1beta1'
  test-integration_waas_v2:
    name: 'waas/v2'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: 'waas/v2'
        uses: ./
        with:
          version: 'waas/v2'
  test-integration_waas_v2latest:
    name: 'waas/latest'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: 'waas/latest'
        uses: ./
        with:
          version: 'waas/latest'
  integrity:
    runs-on: ubuntu-latest
    steps:
    - name: checkout repo
      uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: '16'
    - name: Build action
      run: |
        npm ci &&
        npm run build &&
        rm -rf ./node_modules &&
        npm ci --production
    - name: Test Action
      run: |
        npm run test:build:ci
    - name: Repository Integrity Check
      run: |
        git diff --quiet dist
  automerge:
    name: Automerge Dependabot PRs
    if: >
        github.event_name == 'pull_request' &&
        github.event.pull_request.user.login == 'dependabot[bot]'
    needs:
      - lint
      - test-unit
      - test-integration_waas_v1alpha3
      - test-integration_waas_v1alpha4
      - test-integration_waas_v1beta1
      - test-integration_waas_v2
      - test-integration_waas_v2latest
      - integrity
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: write
    steps:
      - uses: fastify/github-action-merge-dependabot@v3.4.2
        with:
          exclude: '@actions/core,@actions/tool-cache'
