name: "build-test"
on: # rebuild any PRs and main branch changes
  pull_request:
  push:
    branches:
      - main
      - "releases/*"

jobs:
  build: # make sure build/ci work properly
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - run: |
          npm install
      - run: |
          npm run build
      - run: |
          npm run test
  test: # make sure the action works on a clean machine without building
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./
        with:
          version: "waas/v1alpha3"
      - uses: ./
        with:
          version: "waas/v1alpha4"
      - uses: ./
        with:
          version: "waas/v1beta1"
